### ISSUE TITLE
How to upload file?

### ISSUE THREAD

**Issue by blackfyre** [thecanarycollective/station#3]
How can a field be created for file upload?

**Comment by phirschybar** [comment]
@blackfyre - we are lacking documentation right now unfortunately :(

An example of an upload field in a panel definition file is this:

```
'logo' => [
		'label'			=> 'Color Logo Image',
		'help' 			=> '(270 x 270 min)',
		'type'			=> 'image',
		'rules'			=> '',
		'display'		=> 'CRUD',
		'allow_upsize' 	=> TRUE,
		'sizes' 		=> [
			'original' 	=> ['label'=>'Original'],	
			'logo-300x150'	=> ['label'=>'300 x 150','size'=>'300x150', 'letterbox' => '#FFFFFF'],
			'logo-270x270'	=> ['label'=>'270 x 270','size'=>'270x270', 'letterbox' => '#FFFFFF'],
			'logo-180x180'	=> ['label'=>'180 x 180','size'=>'180x180', 'letterbox' => '#FFFFFF'],
		]
	],
```

The key `logo` is the DB field name. The array of `sizes` indicates the various sizes which will be auto-cropped to. The images can also be further cropped  via drag/select crop system. 

You can define S3 (station only support S3 file upload right now) credentials in your `_app.php` config file.

Hope this helps. We are all so busy it's been difficult finding the time to create docs. Happy to answer questions!

**Comment by blackfyre** [comment]
Thanks for the answer :smile: 
And just a friendly advice: maybe you could extend the wiki as a documentation as the questions come along :wink:

**Comment by phirschybar** [comment]
@blackfyre - we will do that for sure. Thanks for the tip :)
